language: node_js
node_js:
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'

jobs:
  include:
    - stage: npm release
      if: tag IS present
      deploy:
        provider: npm
        email: rogier+npm@konfirm.eu
        on:
          branch: master
          tags: true
        api_key:
          secure: oFlTq3DJ/LnsDXBc37zsH44NT2G/oPhPLXxDoPYu7+d1uaGPIqmMHcLomrEB+NGrif9JMdftZfryOy4q5mj8PItOHDXBYTuwAqfqa3hIJfWEaDH/ZxWraXRYk+nMXGH6LM4Qj2e9K1mVO+qFmDVpiHputRKLMHJBmYbSuWJJSZFdsGdJ9qbU9oNq5vsjNxYO7z4N4RiT3kbzSNzCjvreNxfm4OJYA/9y4J6OPWZet4sHZg/Enkmrj4AwbuopPDeCkryzJcE6Ky2phPbf+jPf7cNpSjP2S2WDB0tJnjKq2Q20GPVZFAmDbHouoxLMJU0py6B4UFJcZhX/Tn8Ck1HBdIjnhRtdkPVYXe712mR/gKHH2+cdtANJ4q+vze1p1J+k91//5Clq/D1QdfWj7IInmwm+rzvZj2Xq5dX4/A/FCMkrF+5ZWmpavb8eB13Dk0kJUprarRvCBzU3NA3DIwOdPX/qwPP6Tzyz/CDQj5b6UcBVbRtnwl+xd+Q+huhpTPJGycQuQIYFtOXP51I8Yj2q+GreRclabz+R7QwlinfYJrLFUFcRbMeQDqFexTqbMs/wE3lCsJOp+bNqBADi8rtk1CHtssKqVI6ocg5xPtqmsJKjMrTFvsHQqBmeQoeBBeTS84Pg6fSYxmA5G6XfyX/75hfzlsIL9sFGN1lN/DFYX4w=
